### PR TITLE
description: Display node's URL.

### PR DESCRIPTION
**Pull request by jaka**
Work in progress.

### CODE REVIEW

**Comment by kostko** [comment]
This looks good, does it work correctly (besides the commit message)?

**Comment by mitar** [comment]
No. @jaka reported that for some reason it does not display anything anymore. While before with old approach it did.

**Comment by kostko** [comment]
Not sure why this worked before, but you seem to be missing

```
{% load i18n %}
```

at the top of the `url.html` template file (you are using the `trans` tag, which is only available after you load the `i18n` template tag module).

With this change, everything works for me. Please amend your commit, also fixing the commit message.

**Comment by jaka** [comment]
Sorry for delay. I updated `url.html` and changed commit message.

**Comment by kostko** [comment]
Please rebase on development branch.

**Comment by jaka** [comment]
I think I managed to rebase to the latest development branch.

**Review by kostko — APPROVED** [review]

**Pull request merged**
