### PR TITLE
Fix building

### PR DESCRIPTION
**Pull request by robimarko**
Fix building cause by pulling pip 10.0.1 release as the current one.
That one is broken on all distros and cause docker-compose build to exit with no such option: --allow-all-external error.
--allow-all-external got removed with 10.0.0.
Fixing pip to latest known to work 9.0.3 fixes that.

### CODE REVIEW

**Comment by mitar** [comment]
Great catch! Why do we even use `allow-all-external`? And why is CI still failing?

**Comment by robimarko** [comment]
I dont know why do we use it.
It used to enable checksum checking agains pypi when stuff was pulled from third party sources.

I dont know why is CI failing on PostgreSQL version check.
Can you restart the CI build?

**Comment by mitar** [comment]
You cannot restart CI build? You should be able. Login into Travis.

**Comment by robimarko** [comment]
Yeah,I was not logged in.
It failed again on the same error.
It looks like that error is caused by psycopg2 version being too old.
I gotta test that.

I think that --allow-all-external is now default behavior in pip 10 but I gotta test it so we can remove the hard-coded dependency.

Also,during GSOC I gotta get around to updating packages as a lot of them are way out of date.

**Pull request merged**
