### PR TITLE
description: Display node's URL.

### PR DESCRIPTION
**Pull request by jaka**

### CODE REVIEW

**Review by kostko — CHANGES_REQUESTED** [review]
Nice work!

But, your code is in the wrong module. Since the description configuration is provided in `nodewatcher.modules.administration.description`, the URL partial should be placed there.

**Review by kostko — CHANGES_REQUESTED** [review]
Also, the commit author's e-mail address doesn't seem to be linked to your GitHub account. Can you also update this?

**Review by kostko — CHANGES_REQUESTED** [review]
And another thing, please update your commit message to include the module name prefix, as the change only applies to one module.

Something like:

```
description: Display node's URL.
```

**Comment by jaka** [comment]
OK, I'll fix this. I just added code to the place where I found similar code.

**Pull request closed without merging**
