### PR TITLE
Add Edgerouter X device descriptor

### PR DESCRIPTION
**Pull request by robimarko**
Pull request to add Ubiquti Edgerouter X device descriptor.
This time properly made in separate branch.

### CODE REVIEW

**Comment by robimarko** [comment]
@kostko Does Nodewatcher include CPU port in ports variable?

**Comment by kostko** [comment]
> @kostko Does Nodewatcher include CPU port in ports variable?

No, the `ports` must include the CPU port identifier, otherwise this is an error. This is why you are getting the following exception:
```
ImproperlyConfigured: Switch descriptor 'sw0' refers to an invalid CPU port '6'!
```

You configured `ports=5` on the switch, but the switch as you defined it actually has 7 ports (e.g., 0, 1, 2, 3, 4, 5, 6), not just 5. So it should be `ports=7`.

**Comment by robimarko** [comment]
I get I know.
I did not know that it has to include CPU port as well.

According to Lede source and actuall running Lede on ERX port 5 is not being used.
And port 6 is CPU.

Ok,will edit config to 7 ports.
Have you checked out Unifi PR#38?

**Comment by kostko** [comment]
> According to Lede source and actuall running Lede on ERX port 5 is not being used.

You do not need to specify sequential ports, instead of `ports=7` you can say `ports=[0, 1, 2, 3, 4, 6]` and then port 5 will be invalid.

**Comment by robimarko** [comment]
Thanks,that makes sense.
Also thanks for patience

**Comment by robimarko** [comment]
Should be fixed now

**Comment by robimarko** [comment]
Just figured out that I had wrong device profile for making defined.
Now it is per LEDE profile.
@kostko @mitar Any chance of merging?

**Comment by robimarko** [comment]
I have squashed previous commits into one.

**Comment by robimarko** [comment]
@kostko Is ramips_mt7621 builder ready?

**Comment by kostko** [comment]
> @kostko Is ramips_mt7621 builder ready?

Yes.

**Review by kostko — APPROVED** [review]
Looks good, I think we can merge and you can fix things if somethihng shows itself to be wrong.

**Comment by robimarko** [comment]
Sure, that would be great.

**Pull request merged**
